name: Build and test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6

    - name: Install clang-format
      run: sudo apt install -y clang-format

    - name: Check formatting
      run: make format_check

    - name: Compile library and tests
      run: make

    - name: Test
      run: make test
